ARG NODE_VERSION=20

FROM node:${NODE_VERSION}-alpine AS build

ENV NODE_ENV=production
ARG GITHUB_PAT
ENV GITHUB_PAT=${GITHUB_PAT}

WORKDIR /usr/src/app

COPY .npmrc ./.npmrc
COPY package.json package.json
COPY package-lock.json package-lock.json

RUN npm ci --omit=dev

COPY . .

FROM node:${NODE_VERSION}-alpine

WORKDIR /usr/src/app
# need to COPY node_modules 
COPY --from=build /usr/src/app/src src/

CMD node src/index.js